### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by LouKev** [saucer/saucer#60]
### ✍️ Bug Description

Did you pushed new commit under already created tags ?

We used to compile a saucer and saucer desktop app with this tags : v6.0.1 & 3.0.0.
I now get this error : 

error: ‘struct saucer::application::impl’ has no member named ‘iteration’
m_parent->native<false>()->iteration();

If i go to the newest desktop tag 4.0.2 I get :

fatal error: saucer/error/error.hpp: Aucun fichier ou dossier de ce nom
#include <saucer/error/error.hpp>

I compile on a 24.04 ubuntu. I tried under 25.10 one but same result.

### 🔁 Steps to reproduce

gcc (Ubuntu 14.2.0-4ubuntu2~24.04) 14.2.0
cmake version 3.28.3

Compile an app user saucer & saucer desktop. Compilation failure.

### 🛸 Saucer Version

v6.0.1

### 🖥️ Operating System

Linux

### 🧰 Compiler

gcc

### 📦 Environment

libwebkitgtk-6.0-dev :  2.48.5-0ubuntu0.24.04.1

### 🖥️ Distribution

Ubuntu 24.04

### ✅ I confirm that...

- [x] I have collected all the required information and read all the comments in this document
- [x] I searched for an existing bug report for this issue
- [x] the problem does occur with the reproduction steps I provided
- [x] what I described is indeed a problem
